version: '3'

services:
  nlw_class_1:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: nlw_class_1
    container_name: nlw_class_1
    ports:
      - '3333:3333'
    command: npm run dev
